# Source: https://raw.githubusercontent.com/BDav24/gekko/develop/config/strategies/custom-vix-fix.toml
# Note: to launch just before candle size multiple (Ex: 10:14:58)
pair = 'BTC-EUR'
candleSize = 900 # 15 minutes
loadInitialCandles = false
slackNotification = false
